version: "3.7"

services:
## Video Hosting
  jellyfin:
    container_name: jellyfin
    image: cr.hotio.dev/hotio/jellyfin
    ports:
      - "8096:8096"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ./jellyfin:/config
      - /data/media:/data
      - /extend/media:/data2
      ### VAAPI Devices required for hardware accelerated transcoding (especially of HEVC)
      ## Uncommend all the lines below to enable hardware acceleration
      # - /dev/dri/renderD128:/dev/dri/renderD128
      # - /dev/dri/card0:/dev/dri/card0
    # devices:
      # - /dev/dri/renderD128:/dev/dri/renderD128
      # - /dev/dri/card0:/dev/dri/card0